export const products = [
  {
    imgUrl: 'https://picsum.photos/200/300',
    title: 'Product 1',
    rating: 4,
    reviews: [
      {
        userImage: 'https://randomuser.me/api/portraits/men/1.jpg',
        userName: 'John Doe',
        description: 'Great product!',
        rating: 5,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/1.jpg',
        userName: 'Jane Smith',
        description: 'Very useful.',
        rating: 4,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/men/2.jpg',
        userName: 'Alice Johnson',
        description: 'Good quality.',
        rating: 4,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/2.jpg',
        userName: 'Bob Brown',
        description: 'Satisfactory.',
        rating: 3,
      },
    ],
    sold: 200,
    price: 150000,
    discountPrice: 120000,
    description: 'This is a great product.',
  },
  {
    imgUrl: 'https://picsum.photos/200/300',
    title: 'Product 2',
    rating: 5,
    reviews: [
      {
        userImage: 'https://randomuser.me/api/portraits/men/3.jpg',
        userName: 'Emily Black',
        description: 'Excellent!',
        rating: 5,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/3.jpg',
        userName: 'Frank Clark',
        description: 'Exceeded my expectations.',
        rating: 5,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/men/4.jpg',
        userName: 'Grace Lewis',
        description: 'Highly recommended.',
        rating: 5,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/4.jpg',
        userName: 'Hannah Adams',
        description: 'Fantastic quality!',
        rating: 5,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/men/5.jpg',
        userName: 'Ian Carter',
        description: 'Very happy with the purchase.',
        rating: 5,
      },
    ],
    sold: 300,
    price: 200000,
    discountPrice: undefined,
    description: 'High quality product.',
  },
  {
    imgUrl: 'https://picsum.photos/200/300',
    title: 'Product 3',
    rating: 3,
    reviews: [
      {
        userImage: 'https://randomuser.me/api/portraits/men/6.jpg',
        userName: 'Jessica Miller',
        description: 'Average.',
        rating: 3,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/5.jpg',
        userName: 'Kevin Anderson',
        description: 'Could be better.',
        rating: 3,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/men/7.jpg',
        userName: 'Lily Scott',
        description: 'Not bad.',
        rating: 3,
      },
    ],
    sold: 150,
    price: 100000,
    discountPrice: 85000,
    description: 'Good for the price.',
  },
  {
    imgUrl: 'https://picsum.photos/200/300',
    title: 'Product 4',
    rating: 4,
    reviews: [
      {
        userImage: 'https://randomuser.me/api/portraits/men/8.jpg',
        userName: 'Michael Jones',
        description: 'Good quality!',
        rating: 4,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/6.jpg',
        userName: 'Nina Walker',
        description: 'Very good.',
        rating: 4,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/men/9.jpg',
        userName: 'Olivia Wright',
        description: 'Satisfactory.',
        rating: 4,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/7.jpg',
        userName: 'Paul Wilson',
        description: 'Worth the money.',
        rating: 4,
      },
    ],
    sold: 180,
    price: 120000,
    discountPrice: 100000,
    description: 'Reliable and affordable.',
  },
  {
    imgUrl: 'https://picsum.photos/200/300',
    title: 'Product 5',
    rating: 2,
    reviews: [
      {
        userImage: 'https://randomuser.me/api/portraits/men/10.jpg',
        userName: 'Quinn Rogers',
        description: 'Not as expected.',
        rating: 2,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/8.jpg',
        userName: 'Riley Harris',
        description: 'Disappointing quality.',
        rating: 2,
      },
    ],
    sold: 90,
    price: 50000,
    discountPrice: 45000,
    description: 'Lower quality compared to others.',
  },
  {
    imgUrl: 'https://picsum.photos/200/300',
    title: 'Product 6',
    rating: 4,
    reviews: [
      {
        userImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        userName: 'Sophia Clark',
        description: 'Great value!',
        rating: 4,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/9.jpg',
        userName: 'Thomas Lee',
        description: 'Very useful.',
        rating: 4,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/men/12.jpg',
        userName: 'Uma Smith',
        description: 'Highly recommend.',
        rating: 4,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/10.jpg',
        userName: 'Victoria Lee',
        description: 'Good quality.',
        rating: 4,
      },
    ],
    sold: 220,
    price: 170000,
    discountPrice: 150000,
    description: 'High performance and durable.',
  },
  {
    imgUrl: 'https://picsum.photos/200/300',
    title: 'Product 7',
    rating: 3,
    reviews: [
      {
        userImage: 'https://randomuser.me/api/portraits/men/13.jpg',
        userName: 'Willow Davis',
        description: 'It’s okay.',
        rating: 3,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/11.jpg',
        userName: 'Xander Wright',
        description: 'Not bad.',
        rating: 3,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/men/14.jpg',
        userName: 'Yara Smith',
        description: 'Could be better.',
        rating: 3,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/12.jpg',
        userName: 'Zachary Adams',
        description: 'Average product.',
        rating: 3,
      },
    ],
    sold: 130,
    price: 90000,
    discountPrice: 85000,
    description: 'Average product, decent for the price.',
  },
  {
    imgUrl: 'https://picsum.photos/200/300',
    title: 'Product 8',
    rating: 5,
    reviews: [
      {
        userImage: 'https://randomuser.me/api/portraits/men/15.jpg',
        userName: 'Alex Brown',
        description: 'Fantastic product!',
        rating: 5,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/13.jpg',
        userName: 'Bella Davis',
        description: 'Exceeded expectations.',
        rating: 5,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/men/16.jpg',
        userName: 'Charlie Harris',
        description: 'Will buy again.',
        rating: 5,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/14.jpg',
        userName: 'Daisy Lewis',
        description: 'Top quality!',
        rating: 5,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/men/17.jpg',
        userName: 'Ethan Walker',
        description: 'Highly recommended.',
        rating: 5,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/15.jpg',
        userName: 'Fiona Clark',
        description: 'Absolutely love it.',
        rating: 5,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/men/18.jpg',
        userName: 'George Adams',
        description: 'Perfect.',
        rating: 5,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/16.jpg',
        userName: 'Hannah Wilson',
        description: 'Fantastic buy.',
        rating: 5,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/men/19.jpg',
        userName: 'Ian Carter',
        description: 'Very satisfied.',
        rating: 5,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/17.jpg',
        userName: 'Jessica White',
        description: 'Best purchase ever.',
        rating: 5,
      },
    ],
    sold: 300,
    price: 220000,
    discountPrice: 200000,
    description: 'Premium quality and highly recommended.',
  },
  {
    imgUrl: 'https://picsum.photos/200/300',
    title: 'Product 9',
    rating: 4,
    reviews: [
      {
        userImage: 'https://randomuser.me/api/portraits/men/20.jpg',
        userName: 'Karen Martin',
        description: 'Very good.',
        rating: 4,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/18.jpg',
        userName: 'Leo Thompson',
        description: 'Satisfactory.',
        rating: 4,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/men/21.jpg',
        userName: 'Mia Lewis',
        description: 'Good value for money.',
        rating: 4,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/19.jpg',
        userName: 'Noah Wright',
        description: 'Nice product.',
        rating: 4,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/men/22.jpg',
        userName: 'Olivia King',
        description: 'Solid performance.',
        rating: 4,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/20.jpg',
        userName: 'Paulina Scott',
        description: 'Quite satisfactory.',
        rating: 4,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/men/23.jpg',
        userName: 'Quincy Turner',
        description: 'Recommended.',
        rating: 4,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/21.jpg',
        userName: 'Rachel Green',
        description: 'Good product.',
        rating: 4,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/men/24.jpg',
        userName: 'Steve Mitchell',
        description: 'Very good quality.',
        rating: 4,
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/22.jpg',
        userName: 'Tina Evans',
        description: 'Solid choice.',
        rating: 4,
      },
    ],
    sold: 160,
    price: 130000,
    discountPrice: 110000,
    description: 'Solid product with good features.',
  },
];
