export const carts = [
  {
    id: 1,
    name: 'Premium Jean Jacket',
    price: 125000,
    quantity: 2,
    image: 'https://via.placeholder.com/150?text=Jean+Jacket',
    discountPrice: null,
  },
  {
    id: 2,
    name: 'Elegant Pink Singlet',
    price: 99000,
    quantity: 1,
    image: 'https://via.placeholder.com/150?text=Pink+Singlet',
    discountPrice: null,
  },
  {
    id: 3,
    name: 'Classic Plaid Shirt',
    price: 135000,
    quantity: 3,
    image: 'https://via.placeholder.com/150?text=Plaid+Shirt',
    discountPrice: {originalPrice: 180000, discountPercent: 25},
  },
  {
    id: 4,
    name: 'Cozy Orange Sweater',
    price: 175000,
    quantity: 1,
    image: 'https://via.placeholder.com/150?text=Orange+Sweater',
    discountPrice: {originalPrice: 200000, discountPercent: 12},
  },
  {
    id: 5,
    name: 'Luxury Black T-Shirt',
    price: 95000,
    quantity: 5,
    image: 'https://via.placeholder.com/150?text=Black+T-Shirt',
    discountPrice: null,
  },
  {
    id: 6,
    name: 'Casual Blue Denim',
    price: 150000,
    quantity: 2,
    image: 'https://via.placeholder.com/150?text=Blue+Denim',
    discountPrice: {originalPrice: 180000, discountPercent: 17},
  },
  {
    id: 7,
    name: "Men's White Sneakers",
    price: 225000,
    quantity: 2,
    image: 'https://via.placeholder.com/150?text=White+Sneakers',
    discountPrice: null,
  },
  {
    id: 8,
    name: "Women's Red Dress",
    price: 195000,
    quantity: 1,
    image: 'https://via.placeholder.com/150?text=Red+Dress',
    discountPrice: {originalPrice: 220000, discountPercent: 11},
  },
];
