export const orders = [
  {
    id: 1,
    imgUrl: 'https://picsum.photos/200/300',
    nameOrder: 'Order 1',
    quantity: 1,
    discountPrice: 500000,
    originalPrice: 1000000,
    location: 'Jl. Contoh Destination 1',
    originAddress: 'Jl. Contoh Origin 1',
    shippingCost: 10000,
    voucherDiscount: 20000, // contoh ada voucher discount
  },
  {
    id: 2,
    imgUrl: 'https://picsum.photos/200/300',
    nameOrder: 'Order 2',
    quantity: 1,
    discountPrice: null, // tidak ada discount price
    originalPrice: 2000,
    location: 'Jl. Contoh Destination 2',
    originAddress: 'Jl. Contoh Origin 2',
    shippingCost: 15000,
    voucherDiscount: 0, // contoh tidak ada voucher discount
  },
  {
    id: 3,
    imgUrl: 'https://picsum.photos/200/300',
    nameOrder: 'Order 3',
    quantity: 9,
    discountPrice: 900000,
    originalPrice: 1000000,
    location: 'Jl. Contoh Destination 3',
    originAddress: 'Jl. Contoh Origin 3',
    shippingCost: 20000,
    voucherDiscount: undefined, // contoh tidak ada voucher discount
  },
  {
    id: 4,
    imgUrl: 'https://picsum.photos/200/300',
    nameOrder: 'Order 4',
    quantity: 3,
    discountPrice: 300000,
    originalPrice: 400000,
    location: 'Jl. Contoh Destination 4',
    originAddress: 'Jl. Contoh Origin 4',
    shippingCost: 25000,
    voucherDiscount: 50000,
  },
  {
    id: 5,
    imgUrl: 'https://picsum.photos/200/300',
    nameOrder: 'Order 5',
    quantity: 5,
    discountPrice: 800000,
    originalPrice: 900000,
    location: 'Jl. Contoh Destination 5',
    originAddress: 'Jl. Contoh Origin 5',
    shippingCost: 30000,
    voucherDiscount: null,
  },
  {
    id: 6,
    imgUrl: 'https://picsum.photos/200/300',
    nameOrder: 'Order 6',
    quantity: 2,
    discountPrice: 100000,
    originalPrice: 150000,
    location: 'Jl. Contoh Destination 6',
    originAddress: 'Jl. Contoh Origin 6',
    shippingCost: 20000,
    voucherDiscount: 10000,
  },
  {
    id: 7,
    imgUrl: 'https://picsum.photos/200/300',
    nameOrder: 'Order 7',
    quantity: 4,
    discountPrice: null,
    originalPrice: 500000,
    location: 'Jl. Contoh Destination 7',
    originAddress: 'Jl. Contoh Origin 7',
    shippingCost: 40000,
    voucherDiscount: 25000,
  },
  {
    id: 8,
    imgUrl: 'https://picsum.photos/200/300',
    nameOrder: 'Order 8',
    quantity: 7,
    discountPrice: 600000,
    originalPrice: 700000,
    location: 'Jl. Contoh Destination 8',
    originAddress: 'Jl. Contoh Origin 8',
    shippingCost: 35000,
    voucherDiscount: 50000,
  },
  {
    id: 9,
    imgUrl: 'https://picsum.photos/200/300',
    nameOrder: 'Order 9',
    quantity: 6,
    discountPrice: 400000,
    originalPrice: 600000,
    location: 'Jl. Contoh Destination 9',
    originAddress: 'Jl. Contoh Origin 9',
    shippingCost: 45000,
    voucherDiscount: 30000,
  },
  {
    id: 10,
    imgUrl: 'https://picsum.photos/200/300',
    nameOrder: 'Order 10',
    quantity: 10,
    discountPrice: 700000,
    originalPrice: 900000,
    location: 'Jl. Contoh Destination 10',
    originAddress: 'Jl. Contoh Origin 10',
    shippingCost: 50000,
    voucherDiscount: 100000,
  },
];
