export const products = [
  {
    id: 1,
    imgUrl: 'https://picsum.photos/200/300',
    title: 'Product 1',
    rating: 4,
    reviews: [
      {
        userImage: 'https://randomuser.me/api/portraits/men/1.jpg',
        userName: 'John Doe',
        description: 'Great product!',
        rating: 5,
        date: '2024-08-01',
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/1.jpg',
        userName: 'Jane Smith',
        description: 'Very useful.',
        rating: 4,
        date: '2024-08-02',
      },
      {
        userImage: 'https://randomuser.me/api/portraits/men/2.jpg',
        userName: 'Alice Johnson',
        description: 'Good quality.',
        rating: 4,
        date: '2024-08-03',
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/2.jpg',
        userName: 'Bob Brown',
        description: 'Satisfactory.',
        rating: 3,
        date: '2024-08-04',
      },
    ],
    sold: 200,
    price: 150000,
    discountPrice: 120000,
    description: 'This is a great product.',
    sizes: ['S', 'M', 'L', 'XL'],
    isLike: true,
  },
  {
    id: 2,
    imgUrl: 'https://picsum.photos/200/300',
    title: 'Product 2',
    rating: 5,
    reviews: [
      {
        userImage: 'https://randomuser.me/api/portraits/men/3.jpg',
        userName: 'Emily Black',
        description: 'Excellent!',
        rating: 5,
        date: '2024-08-05',
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/3.jpg',
        userName: 'Frank Clark',
        description: 'Exceeded my expectations.',
        rating: 5,
        date: '2024-08-06',
      },
      {
        userImage: 'https://randomuser.me/api/portraits/men/4.jpg',
        userName: 'Grace Lewis',
        description: 'Highly recommended.',
        rating: 5,
        date: '2024-08-07',
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/4.jpg',
        userName: 'Hannah Adams',
        description: 'Fantastic quality!',
        rating: 5,
        date: '2024-08-08',
      },
      {
        userImage: 'https://randomuser.me/api/portraits/men/5.jpg',
        userName: 'Ian Carter',
        description: 'Very happy with the purchase.',
        rating: 5,
        date: '2024-08-09',
      },
    ],
    sold: 300,
    price: 200000,
    discountPrice: undefined,
    description: 'High quality product.',
    sizes: ['M', 'L', 'XL', 'XXL'],
    isLike: false,
  },
  {
    id: 3,
    imgUrl: 'https://picsum.photos/200/300',
    title: 'Product 3',
    rating: 3,
    reviews: [
      {
        userImage: 'https://randomuser.me/api/portraits/men/6.jpg',
        userName: 'Jessica Miller',
        description: 'Average.',
        rating: 3,
        date: '2024-08-10',
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/5.jpg',
        userName: 'Kevin Anderson',
        description: 'Could be better.',
        rating: 3,
        date: '2024-08-11',
      },
      {
        userImage: 'https://randomuser.me/api/portraits/men/7.jpg',
        userName: 'Lily Scott',
        description: 'Not bad.',
        rating: 3,
        date: '2024-08-12',
      },
    ],
    sold: 150,
    price: 100000,
    discountPrice: 85000,
    description: 'Good for the price.',
    sizes: ['S', 'M', 'L'],
    isLike: true,
  },
  {
    id: 4,
    imgUrl: 'https://picsum.photos/200/300',
    title: 'Product 4',
    rating: 4,
    reviews: [
      {
        userImage: 'https://randomuser.me/api/portraits/men/8.jpg',
        userName: 'Michael Jones',
        description: 'Good quality!',
        rating: 4,
        date: '2024-08-13',
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/6.jpg',
        userName: 'Nina Walker',
        description: 'Very good.',
        rating: 4,
        date: '2024-08-14',
      },
      {
        userImage: 'https://randomuser.me/api/portraits/men/9.jpg',
        userName: 'Olivia Wright',
        description: 'Satisfactory.',
        rating: 4,
        date: '2024-08-15',
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/7.jpg',
        userName: 'Paul Wilson',
        description: 'Worth the money.',
        rating: 4,
        date: '2024-08-16',
      },
    ],
    sold: 180,
    price: 120000,
    discountPrice: 100000,
    description: 'Reliable and affordable.',
    sizes: ['S', 'M', 'L', 'XL'],
    isLike: false,
  },
  {
    id: 5,
    imgUrl: 'https://picsum.photos/200/300',
    title: 'Product 5',
    rating: 2,
    reviews: [
      {
        userImage: 'https://randomuser.me/api/portraits/men/10.jpg',
        userName: 'Quinn Rogers',
        description: 'Not as expected.',
        rating: 2,
        date: '2024-08-17',
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/8.jpg',
        userName: 'Riley Harris',
        description: 'Disappointing quality.',
        rating: 2,
        date: '2024-08-18',
      },
    ],
    sold: 90,
    price: 50000,
    discountPrice: 45000,
    description: 'Lower quality compared to others.',
    sizes: ['M', 'L'],
    isLike: true,
  },
  {
    id: 6,
    imgUrl: 'https://picsum.photos/200/300',
    title: 'Product 6',
    rating: 4,
    reviews: [
      {
        userImage: 'https://randomuser.me/api/portraits/men/11.jpg',
        userName: 'Sophia Clark',
        description: 'Great value!',
        rating: 4,
        date: '2024-08-19',
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/9.jpg',
        userName: 'Thomas Lee',
        description: 'Very useful.',
        rating: 4,
        date: '2024-08-20',
      },
      {
        userImage: 'https://randomuser.me/api/portraits/men/12.jpg',
        userName: 'Uma Smith',
        description: 'Highly recommend.',
        rating: 4,
        date: '2024-08-21',
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/10.jpg',
        userName: 'Victoria Lee',
        description: 'Good quality.',
        rating: 4,
        date: '2024-08-22',
      },
    ],
    sold: 220,
    price: 170000,
    discountPrice: 150000,
    description: 'High performance and durable.',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    isLike: false,
  },
  {
    id: 7,
    imgUrl: 'https://picsum.photos/200/300',
    title: 'Product 7',
    rating: 3,
    reviews: [
      {
        userImage: 'https://randomuser.me/api/portraits/men/13.jpg',
        userName: 'Willow Davis',
        description: 'It’s okay.',
        rating: 3,
        date: '2024-08-23',
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/11.jpg',
        userName: 'Xander Wright',
        description: 'Not bad.',
        rating: 3,
        date: '2024-08-24',
      },
      {
        userImage: 'https://randomuser.me/api/portraits/men/14.jpg',
        userName: 'Yara Smith',
        description: 'Could be better.',
        rating: 3,
        date: '2024-08-25',
      },
      {
        userImage: 'https://randomuser.me/api/portraits/women/12.jpg',
        userName: 'Zachary Adams',
        description: 'Average product.',
        rating: 3,
        date: '2024-08-26',
      },
    ],
    sold: 160,
    price: 120000,
    discountPrice: 100000,
    description: 'Decent quality for the price.',
    sizes: ['M', 'L', 'XL'],
    isLike: true,
  },
];
